name: story_app_intermediate_final
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.7
  intl: any
  json_annotation: ^4.8.0
  location: ^4.4.0
  meta: ^1.8.0
  ndialog: ^4.3.0
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
